services:
  - type: worker
    name: telegram-movie-bot
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: API_ID
        value: "20035684"
      - key: API_HASH
        value: "987a8b7ee93d55e76bb29fce4d8ebf52"
      - key: BOT_TOKEN
        value: "8315587555:AAEB8hCCcXn_FN6SHWyUA_ZWuMWcZf6V8ts"
      - key: SHORTENER_DOMAIN
        value: "earnlinks.in"
      - key: SHORTENER_API
        value: "ef9e633750559"
services:
  - type: web
    name: movie-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://riteshkumarsingh:iX9Eeca9iRTH3buu@cluster0.sqrcqji.mongodb.net/moviecollection?retryWrites=true&w=majority&appName=Cluster0
